name: continous-integration

on:
  push:
    branches-ignore: [ga-ignore-*]
  pull_request:
    branches-ignore: [ga-ignore-*]

env:
  URL: EpitechPromo2028/B-OOP-400-BDX-4-1-arcade-lucas.ludovic

jobs:
    no-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check github repo
              uses: actions/checkout@master
            - name: No test passed
              run:  |
                if [[ "${{ github.repository }}" == "${{ env.URL }}" ]]; then
                  exit 1
                else
                  exit 0
                fi

    check-compilation:
      needs: [no-test-job]
      uses: ./.github/workflows/check-binary.yml
      with:
        executable: arcade

    push-mirror:
      if: github.ref == 'refs/heads/main'
      needs: [check-compilation]
      uses: ./.github/workflows/push-mirror.yml
      with:
        MIRROR_URL: git@github.com:EpitechPromo2028/B-OOP-400-BDX-4-1-arcade-lucas.ludovic.git
      secrets:
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
