name: Check binary
on:
  workflow_call:
    inputs:
      executable:
        required: True
        type: string
    secrets:
      GIT_SSH_PRIVATE_KEY:
        required: true

jobs:
    check-compilation:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Branch
            uses: actions/checkout@main
          - name: Set up SSH key
            run:  |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
          - name: Update submodules
            run: |
                  git submodule update --init --recursive
          - name: Compile Repo
            run:  |
                  mkdir .build
                  cd .build
                  cmake ..
                  cd ..
                  cmake --build .build/.
          - name: Check binary presence
            run: |
                if [ ! -f ./${{ inputs.executable }} ]; then
                    echo "::error title=Binary
                    ERROR::Binary not found"
                    exit 1
                fi
                exit 0
